disabled_rules:
  - force_cast
  - force_try

included:
  - NowPlaying/Scripts

excluded:
  - NowPlaying/Scripts/R.generated.swift
  - NowPlaying/Scripts/Vendors
  - Pods

line_length: 200
file_length: 450
large_tuple: 3
nesting:
  type_level:
    warning: 3
    error: 4
  statement_level:
    warning: 5
    error: 8

identifier_name:
  excluded:
    - id
