disabled_rules:
  - force_cast
  - force_try

included:
  - NowPlaying/Scripts

excluded:
  - NowPlaying/Scripts/R.generated.swift
  - NowPlaying/Scripts/Reactive/RxStoreKit/*.swift
  - Carthage
  - Pods

line_length: 200
file_length: 450

identifier_name:
  excluded:
    - id
