language: objective-c
osx_image: xcode10.2
xcode_project: NowPlaying.xcworkspace
xcode_scheme: NowPlaying
cache:
  directories:
    - Carthage
    - Pods
    - vendor
before_install:
  - export GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
  - gem update bundler -N
  - bundle install --path vendor/bundle
  - bundle exec pod install --repo-update
  - carthage bootstrap --platform iOS --cache-builds
script:
  - sudo security create-keychain -p travis travis.keychain
  - sudo security default-keychain -s travis.keychain
  - sudo security unlock-keychain -p travis travis.keychain
  - sudo security set-keychain-settings -t 3600 -l ~/Library/Keychains/travis.keychain
  - openssl aes-256-cbc -a -d -k $DECORD_CERTS -in certs/GoogleService-Info.plist.enc -out NowPlaying/Resources/GoogleService-Info.plist
  - openssl aes-256-cbc -a -d -k $DECORD_CERTS -in certs/env.enc -out NowPlaying/Resources/.env
  - openssl aes-256-cbc -a -d -k $DECORD_CERTS -in certs/embedded.mobileprovision.enc -out certs/embedded.mobileprovision
  - openssl aes-256-cbc -a -d -k $DECORD_CERTS -in certs/Distribution.p12.enc -out certs/Distribution.p12
  - sudo security import ./certs/ios_distribution.cer -k ~/Library/Keychains/travis.keychain -T /usr/bin/codesign
  - sudo security import ./certs/Distribution.p12 -k ~/Library/Keychains/travis.keychain -P $CERT_PASS -T /usr/bin/codesign
  - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  - cp certs/embedded.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
  - sudo security set-key-partition-list -S apple-tool:,apple: "-s -k travis travis.keychain"
  - set -o pipefail && xcodebuild -workspace NowPlaying.xcworkspace -scheme NowPlaying -configuration Debug COMPILER_INDEX_STORE_ENABLE=NO archive -archivePath ./build/NowPlaying.xcarchive -UseModernBuildSystem=NO | bundle exec xcpretty
  - set -o pipefail && xcodebuild -exportArchive -archivePath ./build/NowPlaying.xcarchive -exportPath ./build/export -exportOptionsPlist ./build/export/export_options.plist | bundle exec xcpretty
env:
  global:
    secure: pFIOMwaJ+v3QUNyf0sIWhy+DA25VCatifCVIr0JGu8sLw7If7VwBW3iL6+VCEsAq+JqDeUzXGuiIzqHjTQDFteQQzGH/gsYkElZlgqqn0lA3OcjwHZX9/9buQw4UCmXfF4W+qQS0rB5jw3SyPH7hWuKy+u1kO8opdiTLRBlTKqPtIPuMchx2PZaZ0Bjs5SPla+5YEGoz7dn8IEXutURoQQTlCvwyg6v7ftgZkpf3tWRqTVJPjHdSALjLJQDx2ZUcR9JnpnZzxest9ZM3R/FOcOf2VlROSChNn1aQVD3eqkg7tsxF4FrhkRMFhmtR1CXdJzvC1h+OXy0toZw9AX4VqcXD0SinzyWfehtfV+E7QsbnBb+av82ejr7tfqC0VMq7X3wvoRwSTkxJF81wLFRBJfIC6BqBRmQwhqGkeqNaVlNohOOjBGGNfrY7jNUYwsuvHe9JUpQDMkzBjbXL2BhcdQ5eGTfTrOWq54MfwVLmVWDYczb60EVw82X+QBsBaXCQpu0IJmZq4lx8RARd+ENLK6JrI3gLT8TveyIwARmlwFpRyhj0ITV6BtwQOWAb6JtR5hA1XeZF2OjM6nUlnAcc7l0jiB+qpH4itva0tVydnY2mNeu1zzQCPPp0AhUh5ViAjBvzBL+T95exO0yQB8jyw5QB45hZcfbKt4b/5oLmwIU=
dd:
  secure: VBYWJVUB866GnEp/g/sMRKbJQYRmi8+Cu1YYAMJzk5J9tj8kltVlp1ymbiZrDwjcNTfnegfpNLXEeA38e+QVSCNo6eE4boZ1Gd6h8X/ziOIJll3bjotJ+FoQKbDRykgmEvT5fvzUfNVxc/YZAV8znXpP8HIXbSyXETPcZj9z+i9v0JyqYz3NbNkH4W1dMNIrw1gTvr5kwZY6Tx3XYk+Y4Hb9dFt3bO+4Hr16NoPa0FGw9orjx3dNBdly5uyIHAqDz2qvgm4aDv4v/1LApO99CkygXSJAxFf0wejOHjU9EKqIZE98TvJ0ipIZsD+X5FRPosyCCuvlAAgL43XxokxZEO2DdhuatzCsJLc154jtwFQ5QPefdUUlgNDZUYjRqUft3iJMHGZ9SVR7a98kqWWFgSFU6R7NMvXHutHH2Dmzmqq6JaEzsBVhx5tfPLsHidgcF0MhC1uDRAz6KauZ3AnwngYjjmyz6O0ea+NCrXFW2HujKnlj/Si8kG04S/32Zu8hV6dAfV0kOHEIvOfSg16C4+N93V3s8YzkrvFTc2BD+lZupb7ZkxERsRZaOqIDNXQVLhftoA436JDMwcnmlWVgcWLz2iEj+EAK53avbaKAezY10Dq0UXWgm6IinBdLlROpoKbrfE6KhExSVICNzAyEifG2fx4MyFhjm2k///j2T1U=
branches:
  only:
    - travis/deploygate
