name: NowPlaying

attributes:
    ORGANIZATIONNAME: Yuya Oka

configs:
    Debug: debug
    Release: release

options:
    bundleIdPrefix: moe.nnsnodnb
    developmentLanguage: ja
    usesTabs: false
    indentWidth: 4
    xcodeVersion: 11.1
    deploymentTarget:
        iOS: 11.0

settings:
    base:
        ENABLE_BITCODE: true
        DEVELOPMENT_TEAM: 99649YXF6E
        VALID_ARCHS: arm64
        SWIFT_VERSION: 5.1

targets:
    # Application
    NowPlaying:
        type: application
        platform: iOS
        configFiles:
            Debug: NowPlaying/Resources/Config/NowPlaying-Debug.xcconfig
            Release: NowPlaying/Resources/Config/NowPlaying-Release.xcconfig
        info:
            path: NowPlaying/Resources/Info.plist
            properties:
                CFBundleDevelopmentRegion: ja_JP
                CFBundleDisplayName: NowPlaying
                CFBundleExecutable: $(EXECUTABLE_NAME)
                CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
                CFBundleLocalizations:
                    - ja
                CFBundleName: $(PRODUCT_NAME)
                CFBundlePackageType: APPL
                CFBundleShortVersionString: 2.4.4
                CFBundleURLTypes:
                    - CFBundleTypeRole: Editor
                      CFBundleURLSchemes:
                          - swifter-$(TWITTER_CONSUMER_KEY)
                    - CFBundleTypeRole: Editor
                      CFBundleURLSchemes:
                          - nowplaying-ios-nnsnodnb
                GADApplicationIdentifier: $(FIREBASE_ADMOB_APP_ID)
                LSApplicationQueriesSchemes:
                    - twitter
                    - twitterauth
                    - cydia
                LSEnvironment:
                    FIREBASE_ADMOB_APP_ID: $(FIREBASE_ADMOB_APP_ID)
                    FIREBASE_ADMOB_BANNER_ID: $(FIREBASE_ADMOB_BANNER_ID)
                    MASTODON_INSTANCES_API_TOKEN: $(MASTODON_INSTANCES_API_TOKEN)
                    TWITTER_CONSUMER_KEY: $(TWITTER_CONSUMER_KEY)
                    TWITTER_CONSUMER_SECRET: $(TWITTER_CONSUMER_SECRET)
                LSRequiresIPhoneOS: true
                NSAppleMusicUsageDescription: 音楽再生のためミュージックライブラリにアクセスします
                UIBackgroundModes:
                    - audio
                UILaunchStoryboardName: LaunchScreen
                UIRequiredDeviceCapabilities:
                    - arm64
                UISupportedInterfaceOrientations:
                    - UIInterfaceOrientationPortrait
                UISupportedInterfaceOrientations~ipad:
                    - UIInterfaceOrientationPortrait
                    - UIInterfaceOrientationPortraitUpsideDown
                    - UIInterfaceOrientationLandscapeLeft
                    - UIInterfaceOrientationLandscapeRight
        settings:
            base:
                ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
                TARGETED_DEVICE_FAMILY: 1
                DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
                CODE_SIGN_ENTITLEMENTS: NowPlaying/Resources/NowPlaying.entitlements
            configs:
                Debug:
                    OTHER_SWIFT_FLAGS: $(inherited) -D DEBUG
                Release:
                    OTHER_SWIFT_FLAGS: $(inherited) -D RELEASE
        sources:
            - path: NowPlaying
              excludes:
                  - Resources/Config/NowPlaying-Debug.xcconfig.sample
                  - Resources/Config/NowPlaying-Release.xcconfig.sample
                  - Resources/Settings.bundle/moe.nnsnodnb.NowPlaying.latest_result.txt
            - path: NowPlaying/Scripts/R.generated.swift
              optional: true
              type: file
            - path: NowPlaying/Resources/Config/NowPlaying-Debug.xcconfig
              optiona: true
              type: file
            - path: NowPlaying/Resources/Config/NowPlaying-Release.xcconfig
              optional: true
              type: file
            - path: NowPlaying/Resources/GoogleService-Info.plist
              optional: true
              type: file
        requiresObjCLinking: true
        dependencies:
            - carthage: APIKit
            - carthage: DeallocationChecker
            - carthage: Feeder
            - carthage: KeychainAccess
            - carthage: Hero
            - carthage: Nuke
            - carthage: Realm
            - carthage: RealmSwift
            - carthage: SnapKit
            - carthage: SVProgressHUD
            - carthage: SwifteriOS
            - target: Umbrella
            - target: TodayExtension
              codeSign: false
              embed: true
        preBuildScripts:
            - script: "\"${PODS_ROOT}/R.swift/rswift\" generate \"${SRCROOT}/NowPlaying/Scripts/R.generated.swift\""
              name: R.swift
              inputFiles:
                  - $(TEMP_DIR)/rswift-lastrun
              outputFiles:
                  - $(SRCROOT)/NowPlaying/Scripts/R.generated.swift
        postCompileScripts:
            - script: "${PODS_ROOT}/SwiftLint/swiftlint"
              name: SwiftLint
        postBuildScripts:
            - script: |
                if [[ $CONFIGURATION = "Debug" ]]; then
                  ${PODS_ROOT}/LicensePlist/license-plist --output-path ${SRCROOT}/NowPlaying/Resources/Settings.bundle \
                  --github-token ${GITHUB_ACCESS_TOKEN} \
                  --config-path ${SRCROOT}/NowPlaying/Resources/license_plist.yml \
                  --prefix moe.nnsnodnb.NowPlaying \
                  --suppress-opening-directory
                fi
              name: "LicensePlist"
            - script: "${PODS_ROOT}/Fabric/run"
              name: Crashlytics
              inputFiles:
                  - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
        scheme:
            testTargets:
                - NowPlayingTests

    # UnitTest
    NowPlayingTests:
        type: bundle.unit-test
        platform: iOS
        sources:
            - path: NowPlayingTests
              excludes:
                  - ReferenceImages_*/*
                  - FailureDiffs/*
        dependencies:
            - carthage: FBSnapshotTestCase
            - target: NowPlaying
            - target: Umbrella
        settings:
            base:
                VALID_ARCHS: x86_64

    # TodayExtension
    TodayExtension:
        type: app-extension
        platform: iOS
        sources:
            - path: TodayExtension
        info:
            path: TodayExtension/Info.plist
            properties:
                CFBundleDisplayName: 再生中の音楽
                NSExtension:
                    NSExtensionMainStoryboard: MainInterface
                    NSExtensionPointIdentifier: com.apple.widget-extension
        dependencies:
            - sdk: NotificationCenter.framework
            - target: Umbrella
        settings:
            base:
                PRODUCT_BUNDLE_IDENTIFIER: moe.nnsnodnb.NowPlaying.TodayExtension
                APPLICATION_EXTENSION_API_ONLY: false

    # Umbrella
    Umbrella:
        type: framework
        platform: iOS
        sources:
            - path: Umbrella
              excludes:
                  - Vendors
            - path: Umbrella/Vendors/RxRealmDataSources/Pod/Classes
              group: Umbrella/Vendors/RxRealmDataSources
              type: group
        dependencies:
            - carthage: Action
            - carthage: Differentiator
            - carthage: RxCocoa
            - carthage: RxDataSources
            - carthage: RxRealm
            - carthage: RxRelay
            - carthage: RxSwift
            - carthage: ScrollFlowLabel

schemes:
    NowPlaying:
        build:
            targets:
                NowPlayingTests: [test]
        test:
            config: Debug
            environmentVariables:
                FB_REFERENCE_IMAGE_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages
                IMAGE_DIFF_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/FailureDiffs

    NowPlayingDev:
        build:
            targets:
                NowPlaying: all
                NowPlayingTests: [test]
        run:
            config: Debug
            environmentVariables:
                FB_REFERENCE_IMAGE_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages
                IMAGE_DIFF_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/FailureDiffs
        test:
            config: Debug
            targets:
                - NowPlayingTests

    TodayExtension:
        build:
            targets:
                TodayExtension: all
