default_platform(:ios)

platform :ios do

  desc "Run test"
  lane :test do
    scan(
      devices: ["iPhone 13 Pro (15.2)"]
    )
  end

  desc "Fetch development certificates"
  lane :setup_development_certificates do
    keychain
    match(
      app_identifier: ["moe.nnsnodnb.NowPlaying", "moe.nnsnodnb.NowPlaying.TodayExtension"]
    )
  end

  desc "Fetch adhoc certificates"
  lane :setup_adhoc_certificates do
    keychain
    match(
      type: "adhoc",
      app_identifier: ["moe.nnsnodnb.NowPlaying", "moe.nnsnodnb.NowPlaying.TodayExtension"]
    )
  end

  desc "Archive & export NowPlaying.ipa for Development"
  lane :development do
    setup_adhoc_certificates

    add_badge(alpha: true)

    begin
      gym(
        export_method: "ad-hoc",
        configuration: "Release",
        xcargs: "PROVISIONING_PROFILE_SPECIFIER='match AdHoc moe.nnsnodnb.NowPlaying' BUNDLE_VERSIONS_STRING_SHORT='#{generate_version_name}'",
      )
    rescue => e
      puts e
    ensure
      sh("git", "restore", "--", "#{Dir.pwd}/../NowPlaying/Resources/Assets.xcassets/")
    end

    upload_symbols_to_crashlytics(
      gsp_path: "./NowPlaying/Resources/Firebase/GoogleService-Info.plist",
    )
  end

  lane :create_appicon do
    appicon(
      appicon_devices: [:iphone, :ios_marketing],
      appicon_path: "NowPlaying/Resources/Assets.xcassets"
    )
  end

  desc "Create keychain if needed"
  private_lane :keychain do
    if is_ci?
      create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: true,
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        add_to_search_list: true,
      )
    end
  end

  desc "Generate version name"
  private_lane :generate_version_name do
    version = get_xcconfig_value(
      path: "./Configurations/NowPlaying.xcconfig",
      name: "BUNDLE_VERSIONS_STRING_SHORT",
    )
    short_hash = last_git_commit[:abbreviated_commit_hash]
    "#{version}-#{short_hash}"
  end
end
