default_platform(:ios)

platform :ios do
  # Match
  desc "Fetch Provisioning Profile & Apple Development Certificate"
  lane :setup_development_certificates do
    keychain
    match(
      type: "development",
    )
  end

  desc "Fetch Provisioning Profile & Apple Distribution Certificate"
  lane :setup_adhoc_certificates do
    keychain
    match(
      type: "adhoc",
    )
  end

  desc "Fetch Provisioning Profile & Apple Distribution Certificate"
  lane :setup_appstore_certificates do
    keychain
    match(
      type: "appstore",
    )
  end

  # Gym
  desc "Gym for AdHoc"
  lane :adhoc do
    setup_adhoc_certificates

    gym(
      export_method: "ad-hoc",
      scheme: "AdHoc",
      xcargs: "MARKETING_VERSION='#{generate_adhoc_marketing_version}'",
    )

    upload_symbols_to_crashlytics(
      gsp_path: "App/AdHoc/AdHoc/GoogleService-Info.plist",
      binary_path: ".swiftpm/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols",
    )

    if is_ci
      firebase_app_distribution(
        app: "1:731011151829:ios:daf43379c91de5c0",
        ipa_path: "Products/AdHoc.ipa",
        groups: "owner",
      )
    end
  end

  desc "Gym for AppStore"
  lane :release do
    setup_appstore_certificates

    gym(
      export_method: "app-store",
      scheme: "Production",
    )

    upload_symbols_to_crashlytics(
      gsp_path: "App/Production/Production/GoogleService-Info.plist",
      binary_path: ".swiftpm/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols",
    )

    if is_ci
      deliver(
        ipa: "Products/Production.ipa",
        precheck_default_rule_level: :error,
      )
    end
  end

  # Utility
  desc "Update MARKETING_VERSION & CURRENT_PROJECT_VERSION"
  lane :update_app_version do
    ["App/AdHoc/AdHoc.xcodeproj", "App/Production/Production.xcodeproj", "App/Develop/Develop.xcodeproj"].each do |xcodeproj|
      version = get_build_number(
        xcodeproj: xcodeproj,
      )
      update_xcodeproj(
        xcodeproj: xcodeproj,
        options: {
          "CURRENT_PROJECT_VERSION": version.to_i + 1,
          "MARKETING_VERSION": "3.0.0",
        }
      )
    end
  end

  # Private
  desc "Create temporary Keychain for CI"
  private_lane :keychain do
    if is_ci
      create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
        default_keychain: true,
        unlock: true,
        timeout: 0,
        lock_when_sleeps: true,
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        add_to_search_list: true,
      )
    end
  end

  desc "Generate MARKETING_VERSION for AdHoc"
  private_lane :generate_adhoc_marketing_version do
    version = get_version_number(
      xcodeproj: "App/AdHoc/AdHoc.xcodeproj",
      target: "AdHoc",
    )
    short_hash = last_git_commit[:abbreviated_commit_hash]
    "#{version}-#{short_hash}"
  end
end
