name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"

jobs:
  actionlint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: reviewdog/action-actionlint@5be522b94290e249dba9f5daded2f7157733e3d2 # v1.76.1
        with:
          reporter: github-pr-review
          level: warning
