name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"

jobs:
  actionlint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: reviewdog/action-actionlint@a1e3e7ff7b1f7554e043f455cc78803e773c4a88 # v1.79.0
        with:
          reporter: github-pr-review
          level: warning
