name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"

jobs:
  actionlint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: reviewdog/action-actionlint@d290e336d5a743810aef4404f757dc862276d2ae # v1.73.4
        with:
          reporter: github-pr-review
          level: warning
