name: Build

on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - NowPlayingPackage/Sources/DependenciesInterfaces/**
      - NowPlayingPackage/Sources/DependenciesLive/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-dependencies-live:
    name: Build DependenciesLive target
    runs-on: macos-26

    env:
      DEVELOPER_DIR: /Applications/Xcode_26.6.app/Contents/Developer
      TEST_DESTINATION: "platform=iOS Simulator,name=iPhone 17 Pro"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get SwiftPM originHash
        id: get-swiftpm-origin-hash
        run: |
          ORIGIN_HASH="$(jq -c -r '.originHash' NowPlaying.xcworkspace/xcshareddata/swiftpm/Package.resolved)"
          echo "ORIGIN_HASH=${ORIGIN_HASH}" >> "${GITHUB_OUTPUT}"

      - name: Cache Swift Packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache-swiftpm
        timeout-minutes: 20
        with:
          path: .swiftpm
          key: ${{ runner.os }}-swiftpm-${{ steps.get-swiftpm-origin-hash.outputs.ORIGIN_HASH }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: Write IDESkipPackagePluginFingerprintValidatation
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Write IDESkipMacroFingerprintValidation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Xcode build for DependenciesLive
        run: |
          set -o pipefail && \
            xcodebuild \
              -scheme DependenciesLive \
              -workspace NowPlaying.xcworkspace \
              -destination "${TEST_DESTINATION}" \
              -clonedSourcePackagesDirPath .swiftpm \
              -disableAutomaticPackageResolution | xcbeautify
