name: Lint

on: [pull_request]

jobs:
  danger:
    runs-on: macos-12

    permissions:
      statuses: write

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
        cache-version: '1'

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_13.3.1.app/Contents/Developer

    - name: Cache CocoaPods
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    
    - name: Setup dependency
      run: bundle exec pod install

    - name: Run danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger

  actionlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: reviewdog/action-actionlint@v1
      with:
        reporter: github-pr-review
        level: warning
