name: Lint

on: [pull_request]

jobs:
  danger:
    runs-on: macos-12

    permissions:
      pull-requests: write
      statuses: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        cache-version: '1'

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer

    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          ${{ runner.os }}-pods-
    
    - name: Setup dependency
      run: bundle exec pod install

    - name: Run danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger

  actionlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: reviewdog/action-actionlint@v1
      with:
        reporter: github-pr-review
        level: warning

  renovate-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rinchsan/renovate-config-validator@v0.0.12
      with:
        pattern: "*.json"
