name: Renovate

on:
  pull_request:
    paths:
      - NowPlayingPackage/Package.swift

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  precheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    outputs:
      result: ${{ steps.parse.outputs.result }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: tj-actions/changed-files@7dee1b0c1557f278e5c7dc244927139d78c0e22a # v47.0.4
      id: files_changes
      with:
        json: "true"
        quotepath: "false"
        escape_json: "false"

    - name: Parse
      shell: python
      id: parse
      env:
        MODIFIED_FILES: ${{ steps.files_changes.outputs.modified_files }}
      run: |
        import json
        import os


        plain = os.getenv("MODIFIED_FILES", "[]")
        plain = plain.replace("\\\"", "\"")
        modified_files = json.loads(plain)
        resolved_files_path = "NowPlaying.xcworkspace/xcshareddata/swiftpm/Package.resolved"
        result = "resolve" if resolved_files_path not in modified_files else "skip"

        with open(os.getenv("GITHUB_OUTPUT"), "a") as f:
            output = f"result={result}"
            print(output, file=f)


  resolve-swift-packages:
    runs-on: macos-15
    needs: precheck
    if: needs.precheck.outputs.result == 'resolve'

    env:
      DEVELOPER_DIR: /Applications/Xcode_26.3.app/Contents/Developer

    steps:
    - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: nnsnodnb
        repositories: nowplaying-ios

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}

    - name: Get SwiftPM originHash
      id: get-swiftpm-origin-hash
      run: |
        ORIGIN_HASH="$(jq -c -r '.originHash' NowPlaying.xcworkspace/xcshareddata/swiftpm/Package.resolved)"
        echo "ORIGIN_HASH=${ORIGIN_HASH}" >> "${GITHUB_OUTPUT}"

    - name: Cache Swift Packages
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      id: cache-swiftpm
      timeout-minutes: 20
      with:
        path: .swiftpm
        key: ${{ runner.os }}-swiftpm-${{ steps.get-swiftpm-origin-hash.outputs.ORIGIN_HASH }}

    - name: Resolve Swift Packages
      run: xcodebuild -resolvePackageDependencies -scheme Develop -workspace NowPlaying.xcworkspace -clonedSourcePackagesDirPath .swiftpm

    - name: Git Config
      run: |
        git config --global user.email "aoi-chan-bot[bot]@users.noreply.github.com"
        git config --global user.name "aoi-chan-bot[bot]"

    - name: Commit & Push
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        git add NowPlaying.xcworkspace/xcshareddata/swiftpm/Package.resolved
        if git commit -m "Resolve Swift Package"; then
          git push origin "HEAD:${HEAD_REF}"
        fi
