name: SwiftLint

on:
  pull_request:
    paths:
      - ".github/workflows/swiftlint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

jobs:
  swiftlint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: nnsnodnb/action-swiftlint@a353c9762a6c856eac886c6c4f0292e800d6dbb2 # v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          workdir: NowPlayingPackage
          reporter: github-pr-review
          level: warning
          fail_level: error
