name: Test

on:
  pull_request:
    paths:
      - .github/workflows/**
      - App/**
      - NowPlaying.xcworkspace/**
      - NowPlayingPackage/**
      - Gemfile
      - Gemfile.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-15

    env:
      DEVELOPER_DIR: /Applications/Xcode_26.3.app/Contents/Developer
      TEST_DESTINATION: "platform=iOS Simulator,name=iPhone 16 Pro"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get SwiftPM originHash
        id: get-swiftpm-origin-hash
        run: |
          ORIGIN_HASH="$(jq -c -r '.originHash' NowPlaying.xcworkspace/xcshareddata/swiftpm/Package.resolved)"
          echo "ORIGIN_HASH=${ORIGIN_HASH}" >> "${GITHUB_OUTPUT}"

      - name: Cache Swift Packages
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: cache-swiftpm
        timeout-minutes: 20
        with:
          path: .swiftpm
          key: ${{ runner.os }}-swiftpm-${{ steps.get-swiftpm-origin-hash.outputs.ORIGIN_HASH }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: Write IDESkipPackagePluginFingerprintValidatation
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Write IDESkipMacroFingerprintValidation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Make test-result folder
        id: test-result-dir
        run: |
          echo "TEST_RESULTS_DIR=$(mktemp -d)" >> "${GITHUB_OUTPUT}"

      - name: Xcode test for NowPlayingPackageTests
        run: |
          set -o pipefail && \
            xcodebuild test \
              -scheme NowPlayingPackageTests \
              -workspace NowPlaying.xcworkspace \
              -parallel-testing-enabled=YES \
              -destination "${TEST_DESTINATION}" \
              -resultBundlePath "${{ steps.test-result-dir.outputs.TEST_RESULTS_DIR }}/Test-NowPlayingPackageTests.xcresult" \
              -clonedSourcePackagesDirPath .swiftpm \
              -disableAutomaticPackageResolution | xcbeautify

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: test-results
          path: ${{ steps.test-result-dir.outputs.TEST_RESULTS_DIR }}
