name: Test

on:
  pull_request:
    paths:
      - .github/workflows/**
      - App/**
      - NowPlaying.xcworkspace/**
      - NowPlayingPackage/**
      - Gemfile
      - Gemfile.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-26

    env:
      FASTLANE_SKIP_UPDATE_CHECK: 1
      DEVELOPER_DIR: /Applications/Xcode_26.6.app/Contents/Developer

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Ruby
        uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4 # v1.323.0
        with:
          ruby-version: "4.0.7"
          bundler-cache: true

      - name: Get SwiftPM originHash
        id: get-swiftpm-origin-hash
        run: |
          ORIGIN_HASH="$(jq -c -r '.originHash' NowPlaying.xcworkspace/xcshareddata/swiftpm/Package.resolved)"
          echo "ORIGIN_HASH=${ORIGIN_HASH}" >> "${GITHUB_OUTPUT}"

      - name: Cache Swift Packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache-swiftpm
        timeout-minutes: 20
        with:
          path: .swiftpm
          key: ${{ runner.os }}-swiftpm-${{ steps.get-swiftpm-origin-hash.outputs.ORIGIN_HASH }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: Write IDESkipPackagePluginFingerprintValidatation
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Write IDESkipMacroFingerprintValidation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Fastlane tests
        env:
          FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 20
        run: bundle exec fastlane ios tests

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results
          path: ./DerivedData
