name: Test

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  tests:
    runs-on: macos-12

    permissions:
      checks: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        cache-version: '1'

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer

    - name: Setup GoogleService-Info.plist
      uses: DamianReeves/write-file-action@v1.2
      with:
        path: NowPlaying/Resources/Firebase/GoogleService-Info.plist
        contents: |
          ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
        write-mode: overwrite

    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .swiftpm
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('NowPlaying.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-${{ hashFiles('NowPlaying.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          ${{ runner.os }}-swiftpm-

    - name: Run Test
      env:
        FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 20
      run: bundle exec fastlane ios test

    - name: Publish unit test results
      uses: kishikawakatsumi/xcresulttool@v1
      if: success() || failure()
      with:
        path: fastlane/test_output/NowPlaying.xcresult
        show-passed-tests: false
        show-code-coverage: false
