name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    runs-on: macos-12

    permissions:
      checks: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        cache-version: '1'

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_13.3.1.app/Contents/Developer

    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          ${{ runner.os }}-pods-
    
    - name: Setup dependency
      run: bundle exec pod install

    - name: Setup GoogleService-Info.plist
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 -d > ./NowPlaying/Resources/Firebase/GoogleService-Info.plist

    - name: Run Test
      run: bundle exec fastlane ios test

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: fastlane/test_output/report.xml
